# frozen_string_literal: true

# Generated by HuberPilot for Issue #: Add email validation to User model
# Generated at: 2025-09-04 16:31:33 -0300

class EmailValidator
  EMAIL_REGEX = /A[w+-.]+@[a-zd-]+(.[a-zd-]+)*.[a-z]+z/i
  
  def self.valid?(email)
    return false if email.nil? || email.empty?
    EMAIL_REGEX.match?(email)
  end
  
  def self.validate_uniqueness(email, existing_emails)
    !existing_emails.include?(email.downcase)
  end
end
