# frozen_string_literal: true

# Generated by HuberPilot for Issue #: Add comprehensive tests for Task model
# Generated at: 2025-09-04 16:31:19 -0300

require_relative '../../app/models/task'

RSpec.describe Task do
  describe "initialization" do
    it "creates a task with valid attributes" do
      task = Task.new(
        title: "Test Task",
        description: "Test Description"
      )
      
      expect(task.title).to eq("Test Task")
      expect(task.description).to eq("Test Description")
    end
  end
  
  describe "validations" do
    it "is valid with valid attributes" do
      task = Task.new(
        title: "Test Task",
        description: "Test Description"
      )
      
      expect(task.valid?).to be true
    end
    
    it "requires a title" do
      task = Task.new(description: "Test Description")
      expect(task.valid?).to be false
    end
  end
  
  describe "methods" do
    it "can save a task" do
      task = Task.new(
        title: "Test Task",
        description: "Test Description"
      )
      
      expect(task.save).to be true
    end
  end
end
