# frozen_string_literal: true

# Generated by HuberPilot for Issue #: Add comprehensive tests for User model
# Generated at: 2025-09-04 16:30:02 -0300

require_relative '../../app/models/user'

RSpec.describe User do
  describe "initialization" do
    it "creates a user with valid attributes" do
      user = User.new(
        name: "John Doe",
        email: "john@example.com"
      )
      
      expect(user.name).to eq("John Doe")
      expect(user.email).to eq("john@example.com")
    end
  end
  
  describe "validations" do
    it "is valid with valid attributes" do
      user = User.new(
        name: "John Doe",
        email: "john@example.com"
      )
      
      expect(user.valid?).to be true
    end
    
    it "requires a name" do
      user = User.new(email: "john@example.com")
      expect(user.valid?).to be false
    end
    
    it "requires an email" do
      user = User.new(name: "John Doe")
      expect(user.valid?).to be false
    end
  end
  
  describe "methods" do
    it "can save a user" do
      user = User.new(
        name: "John Doe",
        email: "john@example.com"
      )
      
      expect(user.save).to be true
    end
  end
end
