# frozen_string_literal: true

# Generated by HuberPilot for Issue #: Add comprehensive tests for UsersController
# Generated at: 2025-09-04 16:31:08 -0300

require_relative '../../app/controllers/users_controller'

RSpec.describe UsersController do
  let(:controller) { UsersController.new }
  
  describe "GET #index" do
    it "returns a list of users" do
      users = controller.index
      expect(users).to be_an(Array)
    end
  end
  
  describe "POST #create" do
    it "creates a new user" do
      # TODO: Implement test
      expect(true).to be true
    end
  end
end
