# frozen_string_literal: true

# Generated by HuberPilot for Issue #: Create Project model
# Generated at: 2025-09-04 16:31:26 -0300

class Task
  attr_accessor :id, :title, :description, :status, :priority, :due_date, :user_id, :created_at, :updated_at
  
  def initialize(attributes = {})
    @id = attributes[:id]
    @title = attributes[:title]
    @description = attributes[:description]
    @status = attributes[:status] || 'todo'
    @priority = attributes[:priority] || 'medium'
    @due_date = attributes[:due_date]
    @user_id = attributes[:user_id]
    @created_at = attributes[:created_at] || Time.now
    @updated_at = attributes[:updated_at] || Time.now
  end
  
  def valid?
    title.present? && title.length >= 3
  end
  
  def save
    @updated_at = Time.now
    true
  end
end
