# frozen_string_literal: true

# Generated by HuberPilot for Issue #: Create Task model with relationships
# Generated at: 2025-09-04 16:30:07 -0300

class User
  attr_accessor :id, :name, :email, :created_at, :updated_at
  
  def initialize(attributes = {})
    @id = attributes[:id]
    @name = attributes[:name]
    @email = attributes[:email]
    @created_at = attributes[:created_at] || Time.now
    @updated_at = attributes[:updated_at] || Time.now
  end
  
  def valid?
    name.present? && email.present? && EmailValidator.valid?(email)
  end
  
  def save
    @updated_at = Time.now
    true
  end
end
